export const teamMembers = [
  {
    id: 1,
    name: "Guillermo García",
    designation: "CEO & Estrategia",
    image: "/equipo/guillermo-garcia-black.png",
    role: "CEO & Estrategia",
    bio: "Dirige la visión de la agencia y el diseño de estrategias digitales para cada cliente.",
    color: "#9B4DBC",
    glow: "rgba(107,45,124,0.35)",
    initials: "GG",
  },
  {
    id: 2,
    name: "Mikel Salvador",
    designation: "Tech Lead & Desarrollo",
    image: "/equipo/mikel-salvador-black.png",
    role: "Tech Lead & Desarrollo",
    bio: "Arquitecto de las soluciones digitales. Convierte ideas de diseño en productos web reales.",
    color: "#3B82F6",
    glow: "rgba(29,78,216,0.35)",
    initials: "MS",
  },
  {
    id: 3,
    name: "Mateo Werner",
    designation: "Diseño & Creatividad",
    image: "/equipo/mateo-werner-black.png",
    role: "Diseño & Creatividad",
    bio: "Crea identidades visuales y contenido que detiene el scroll y conecta con la audiencia.",
    color: "#EC4899",
    glow: "rgba(236,72,153,0.30)",
    initials: "MW",
  },
  {
    id: 4,
    name: "Moisés González",
    designation: "Social Media & Comunidad",
    image: "/equipo/moises-gonzalez-black.png",
    role: "Social Media & Comunidad",
    bio: "Gestiona las comunidades y campañas de redes sociales que generan engagement real.",
    color: "#10B981",
    glow: "rgba(16,185,129,0.30)",
    initials: "MG",
  },
]
